"""Drums & Rhythm content for the Production reference tool."""

DRUMS_SONG_QUESTIONS = [
    {'id': 'tempo', 'label': 'Tempo', 'options': ['Under 80 BPM', '80–100 BPM', '100–120 BPM', '120–140 BPM', '140+ BPM']},
    {'id': 'feel', 'label': 'Groove feel', 'options': ['Laid back / behind the beat', 'Tight / on the grid', 'Heavy and weighted', 'Light and airy', 'Driving / pushing forward']},
    {'id': 'density', 'label': 'Arrangement density', 'options': ['Sparse (1–4 elements)', 'Medium (5–8 elements)', 'Dense (full arrangement)']},
    {'id': 'tone', 'label': 'Energy / mood', 'options': ['Intimate and quiet', 'Warm and soulful', 'Energetic and driving', 'Dark and brooding', 'Euphoric and powerful']},
]

DRUMS_CONTENT_COUNTS = {
    'styles': 8,
    'techniques': 15,
    'character': 14,
    'problems': 6,
}

DRUMS_STYLES = [
    {
        'id': 'trap-modern',
        'type': 'style',
        'context': {
            'tempo': ['120-140', '135'],
            'density': ['sparse', 'medium'],
            'feel': ['tight', 'driving'],
            'tone': ['dark', 'brooding', 'intimate'],
        },
        'title': 'Trap / Modern Hip-Hop',
        'oneLiner': 'Sparse kick, hi-hat rolls, 808 snare. Space is the point.',
        'filters': ['hip-hop', 'electronic'],
        'sections': {
            'sound': 'Sound: Kick on beat 1 (sometimes beat 3), snare replaced by 808-tuned claps or rimshots on 2 and 4, and rolling 16th-note hi-hats with heavy velocity automation — quiet to loud swells within a single bar. The trap hi-hat roll is not random: it accelerates into phrase endings, drops out for impact, then rebuilds. Sub-bass 808 fills harmonic space below. The overall pattern is often shockingly empty — the silences between hits carry as much weight as the hits themselves.',
            'emotion': 'Emotion: Cold, hypnotic, focused, threatening. Emotional weight comes from the space and the 808 melody underneath, not the drums themselves.',
            'whenUse': 'When to use: Hip-hop with melodic or dark tone, 130–165 BPM. When the vocal carries all the narrative weight and drums should support without competing. Dark pop, SoundCloud-era aesthetics.',
            'whenNot': 'When not to use: Warm organic tracks, anything needing live band energy. The mechanical hat grid will fight a natural, airy sound.',
            'build': 'Build: Kick — one-shot 808 kick (Roland TR-808 or sample), tuned to the root of the song. Snare — layered 808 snare + rimshot at low velocity (the 808 snare provides the sub crack). Hats — 16th note grid, velocity automation from 30 to 110 across 4–8 notes for each swell. Open hat as accent on the "and" of beat 2 or 4. Pattern: K . . . . . S . . . . . S . . on the 16th-note grid. Triplet variation (the Migos "offset" pattern): group hats in triplets on the 4th beat — feels like the bar is leaning forward.',
            'signalChain': 'Signal chain: Kick: HPF 30Hz → Transient shaper (attack −3, sustain +2) → 1176 (fast attack, 4:1). Snare: Waves CLA-76 (fast, 8:1) → Waves OneKnob Driver (subtle). Hats: HPF 8kHz → Waves H-Comp (gentle). Bus: Waves SSL G-Bus (2:1, subtle glue).',
            'keyTip': 'Key tip: The hat velocity swell is not random — it always accelerates toward a resolution point (phrase end, snare hit, bar 4). Random velocity = no groove. Intentional velocity = trap. Program the swell as a deliberate shape: a crescendo from velocity 25 to 110 over 8 16th notes into a snare hit.',
            'references': 'References: Travis Scott (Antidote, SICKO MODE), Future (Mask Off), 21 Savage, Young Thug, Gunna. Metro Boomin, Southside, TM88 as production reference.',
        },
        'meta': {'tag': 'Hip-Hop'},
    },
    {
        'id': 'boom-bap',
        'type': 'style',
        'context': {
            'tempo': ['80-100'],
            'feel': ['laid back', 'behind'],
            'tone': ['warm', 'soulful'],
        },
        'title': 'Boom Bap / Classic Hip-Hop',
        'oneLiner': 'Sample-based kick and snare with swing. The MPC feel.',
        'filters': ['hip-hop'],
        'sections': {
            'sound': 'Sound: Kick on 1 and 3 (with variations), snare on 2 and 4, 16th-note hi-hats with MPC-style swing (54–58% swing quantization). The kick has a short, punchy thud — not the long sustain of an 808. The snare has crack and body: often a layered sample with a high mid presence. Hi-hats are swung — the "and" of every beat lands slightly late, creating a loping, deliberate feel. The whole pattern breathes and leans back rather than driving forward.',
            'emotion': 'Emotion: Confident, grounded, purposeful. The swing creates a head-nodding quality — the body wants to move forward but the drums keep pulling it back. Tension and release built into the timing itself.',
            'whenUse': 'When to use: Conscious hip-hop, introspective rap, modern throwbacks to the 90s. 85–100 BPM. When the producer wants the music to feel deliberate and musical rather than cold and mechanical.',
            'whenNot': 'When not to use: Fast trap (140+ BPM), pop with a clean modern grid feel, electronic dance music.',
            'build': 'Build: Source drums from sample libraries or vinyl chops. Kick: one-shot with fast attack (the "boom" — punchy, not long). Snare: layer two samples — one for the body (1–4kHz presence), one for the crack (transient click). Apply MPC-style swing at 54–57% in Ableton (right-click the clip, Warp to groove > MPC 16 Swing 54). Or use Ableton Groove Pool: drag a groove template onto the MIDI clip to shift 16th notes slightly behind the beat. Hi-hats: drawn on the 16th-note grid then swing-quantized. Velocity variation on hats: accent the beat hits, ghost the "and" hits.',
            'signalChain': 'Signal chain: Kick: Waves CLA-76 (medium attack, 4:1, 4–6dB GR) → Waves H-EQ (add 80Hz body, cut 300Hz mud). Snare: Waves SSL E-Channel → Waves CLA-76 (fast, 8:1). Bus: Waves SSL G-Bus Compressor (2:1, slow attack so the transients punch through) → Waves J37 tape saturation (for vinyl warmth).',
            'keyTip': 'Key tip: Swing is not one-size-fits-all. A J Dilla pattern might swing at 54%. A Pete Rock pattern sits closer to 52%. A few percentage points is the difference between a pattern that nods and one that lurches. Program your pattern first at 0% swing, then A/B different swing amounts from 50–60% while the track plays — your body will tell you when it locks in.',
            'references': 'References: J Dilla (Donuts), Pete Rock, Large Professor. Modern: Kendrick Lamar (Good Kid M.A.A.D City — Sounwave), Joey Bada$$ (Capital STEEZ). Questlove as the live-drumming equivalent of this feel.',
        },
        'meta': {'tag': 'Hip-Hop'},
    },
    {
        'id': 'neo-soul-rb',
        'type': 'style',
        'context': {
            'tempo': ['under 80', '80-100'],
            'feel': ['laid back', 'behind', 'heavy'],
            'density': ['sparse', 'medium'],
            'tone': ['warm', 'soulful', 'intimate'],
        },
        'title': 'Neo-Soul / R&B Groove',
        'oneLiner': 'Ghost notes, shuffle feel, live drumming vocabulary in the box.',
        'filters': ['r&b', 'soul', 'organic'],
        'sections': {
            'sound': 'Sound: The foundation of neo-soul drumming is ghost notes — very quiet snare hits (velocity 15–35) between the main snare hits on 2 and 4. These ghosts create a constant low-level conversation in the snare, filling the space without taking attention. The kick has variations: instead of always landing on 1 and 3, it anticipates, lands a 16th note early, or adds syncopated hits on the "e" or "ah" of a beat. Hi-hats often shuffle (alternating 8th and dotted-8th patterns) rather than sit on a straight 16th grid.',
            'emotion': 'Emotion: Warm, alive, breathing. Feels like a person played it — because the vocabulary comes entirely from real drumming. Intimate, soulful, conversational.',
            'whenUse': 'When to use: R&B, neo-soul, soul-influenced pop, any track where the feel matters more than the grid. Frank Ocean, SZA, Anderson .Paak. Slower tempos (70–100 BPM) where the ghost notes have room to breathe.',
            'whenNot': 'When not to use: High-energy dance, trap, pop that needs a clean modern grid feel. Ghost notes at 130+ BPM turn into a wash rather than a conversation.',
            'build': 'Build: Start with snare on 2 and 4 at full velocity (100–110). Add ghost notes at velocity 20–35 on the 16th-note positions around each main hit — typically the 16th before and after the main snare. Kick: start with the 4/4 placement then add syncopated hits — a hit on the "e" of beat 1 (anticipating beat 2), a hit on the "ah" of beat 3. These anticipations create a forward lean within a laid-back feel. Hi-hats: try a shuffle pattern — long-short-long-short on 8th notes, or a 6-note triplet feel over 2 beats.',
            'signalChain': 'Signal chain: Kick: Waves CLA-2A (slow, program-dependent compression) → Waves Scheps 73 (warm low-mid EQ). Snare: Waves SSL E-Channel (HPF 150Hz, narrow boost at 3kHz for presence) → Waves CLA-76 (slow attack to let transients through). Ghost note snare often rides in the same channel — velocity handles the dynamic difference. Bus: Waves J37 tape saturation at very low drive (12–15%) for warmth and glue.',
            'keyTip': 'Key tip: The ghost notes must be quiet enough that they are felt but not heard. If you can identify them as snare hits, they\'re too loud. Set them at 20–30 velocity and then mix them down further in the channel. The correct level is when removing them makes the pattern feel slightly less alive — that\'s the contribution they\'re making.',
            'references': 'References: Questlove (The Roots, D\'Angelo — Voodoo, Erykah Badu). James Gadson (Bill Withers — Ain\'t No Sunshine). Modern: D\'Angelo (Black Messiah), SZA (Kill Bill, Snooze), Frank Ocean (Pyramids), Anderson .Paak.',
        },
        'meta': {'tag': 'R&B / Soul'},
    },
    {
        'id': 'four-on-the-floor',
        'type': 'style',
        'context': {
            'tempo': ['120-140', '100-120'],
            'feel': ['tight', 'driving'],
            'density': ['medium', 'dense'],
            'tone': ['euphoric', 'powerful', 'energetic'],
        },
        'title': 'Four-on-the-Floor / Electronic Dance',
        'oneLiner': 'Kick every beat, driving energy, functional for dance floors.',
        'filters': ['electronic', 'dance'],
        'sections': {
            'sound': 'Sound: Kick on every quarter note (beats 1, 2, 3, 4). Snare or clap on 2 and 4. Open hi-hat on the "and" of beat 2 (or 4) for lift. The kick is the pulse that the whole track breathes around — it must be consistent, punchy, and sit cleanly in the sub-bass range. The snare provides lift and the off-beat hats create forward motion. Everything else in the arrangement sidechains to the kick.',
            'emotion': 'Emotion: Euphoric, driving, relentless, functional. Designed to lock bodies into movement. The kick is a physical event — at full volume in a club it\'s felt in the chest before it\'s heard.',
            'whenUse': 'When to use: Dance-pop, house, electropop, any track designed for a club or festival context. 120–135 BPM. When the music needs to drive and propel rather than groove and sway.',
            'whenNot': 'When not to use: Intimate or emotional contexts where the relentless pulse would feel mechanical. Soul, R&B, hip-hop. The four-on-the-floor kicks away any vulnerability in a vocal.',
            'build': 'Build: Kick — sample with fast transient click (3–8kHz) and sub body (60–80Hz). Check in mono on small speakers: the click is what translates, not the sub. Tune kick to the root of the song or the tonic. Snare/clap: layer two sounds — one for body, one for crack. Clap sample adds width if panned ±5–10% L/R. Open hat: on the "and" of beat 2 (gives lift and release). Closed hat: straight 8ths or 16ths between kick hits. Pattern: K . K . K . K . (quarter notes). Sidechain all pads, bass, and synths to this kick at 4:1 ratio.',
            'signalChain': 'Signal chain: Kick: HPF 30Hz → Transient shaper (enhance attack, reduce sustain for punch) → Waves CLA-76 (fast attack, 4:1) → Waves RBass (enhance sub if needed). Snare: Waves SSL G-Channel → Waves CLA-76 (fast, 8:1). Bus: Waves SSL G-Bus (gentle 2:1 glue) → Waves L2 (soft limiting to control transients).',
            'keyTip': 'Key tip: The kick translates on a phone because of its transient click, not its sub. Test your kick on laptop speakers — if you can\'t hear it, the click layer is too quiet. A kick that\'s all sub and no click will disappear on anything smaller than a subwoofer. The sub and click are separate layers that serve different playback systems.',
            'references': 'References: Calvin Harris, Disclosure, Daft Punk (Discovery, Random Access Memories). Chinchilla (Cut You Off) as a modern example of a kick that works at festival scale. French house approach: Modjo, Cassius.',
        },
        'meta': {'tag': 'Electronic'},
    },
    {
        'id': 'live-acoustic',
        'type': 'style',
        'context': {
            'tempo': ['under 80', '80-100'],
            'feel': ['laid back', 'light'],
            'density': ['sparse', 'medium'],
            'tone': ['warm', 'soulful', 'intimate'],
        },
        'title': 'Live Acoustic / Studio Kit',
        'oneLiner': 'A real drummer captured well. Natural dynamics, overhead-led character.',
        'filters': ['organic', 'rock', 'soul'],
        'sections': {
            'sound': 'Sound: Natural dynamics from the player, room reflections, stick hits heard as much as drum hits. The overhead microphones capture the whole kit as a single instrument — the hi-hats bloom and decay, the cymbals have complex shimmer, the snare has room in it. Close mics (kick, snare, toms) add punch and definition. The total sound is the blend between the overheads (the "picture") and the close mics (the "punch").',
            'emotion': 'Emotion: Human, warm, communal. Signals that real people made this together. The small imperfections in timing and dynamics are not mistakes — they are the soul.',
            'whenUse': 'When to use: Singer-songwriter, folk-rock, organic pop, blues, jazz-influenced R&B. Any context where the music is meant to feel like a gathering of people rather than a computer output. Amy Winehouse, The National, Jack Johnson territory.',
            'whenNot': 'When not to use: Highly quantized electronic production — the live kit will sound out of place. Dark minimal hip-hop. Any track where you need a perfectly consistent metronomic pulse.',
            'build': 'Build (recording): Capture overheads in XY or ORTF configuration — this is the most important thing. Close mics on kick (inside and outside), snare (top and optional bottom), hi-hat. The kit sounds like the overheads; the close mics are correction tools. Blend: start with overheads at 0dB fader. Add kick close mic for punch. Add snare close mic for crack. Stop adding when it sounds like a recorded kit, not like individual drum sounds.\nBuild (sample/plugin): If using drum samples or a plugin (e.g., Superior Drummer, BFD), the same philosophy applies: start with the room/overhead signal as the primary source. Turn down the close mic layer and bring it up only until it adds punch without dominating.',
            'signalChain': 'Signal chain: Overhead L/R: Waves SSL E-Channel (HPF 90Hz, gentle high shelf boost at 12kHz) → Waves CLA-2A (very slow, just catching peaks). Kick: HPF 30Hz → Waves F6 (cut 250Hz mud, boost 80Hz body, boost 3–4kHz click) → Waves CLA-76 (fast, 4:1). Snare: Waves SSL E-Channel → Waves CLA-76 (fast, 8:1, 6dB GR). Bus: Waves SSL G-Bus Compressor (slow attack, 2:1 glue) → Waves J37 (subtle tape warmth).',
            'keyTip': 'Key tip: Phase alignment between the kick close mic and the overheads is the single most important technical issue in drum recording. If the kick close mic and the overhead are slightly out of phase with each other, the low end of the kick cancels and the whole mix loses weight. Zoom in to the waveforms in the DAW and manually nudge the kick close mic forward or back by 1–3ms until the kick sounds fullest.',
            'references': 'References: Amy Winehouse (Back to Black — drummer Remi Kabaka Jr., producer Mark Ronson). The National (drummer Bryan Devendorf — everything by John Congleton). Jack Johnson (drummer Adam Topol — Dan Bern productions).',
        },
        'meta': {'tag': 'Organic'},
    },
    {
        'id': 'lo-fi-sp',
        'type': 'style',
        'context': {
            'tempo': ['under 80', '80-100'],
            'feel': ['laid back', 'behind'],
            'density': ['sparse', 'medium'],
            'tone': ['dark', 'brooding', 'warm', 'intimate'],
        },
        'title': 'Lo-Fi Hip-Hop / SP-404 Aesthetic',
        'oneLiner': 'Dusty samples, filtered warmth, gentle swing. Texture over perfection.',
        'filters': ['hip-hop', 'lo-fi'],
        'sections': {
            'sound': 'Sound: Drum sounds sampled from vinyl, slightly filtered (low-pass at 8–12kHz so the top end is rolled off), with light noise floor and room ambience baked in. The patterns are simple — kick on 1, snare on 2 and 4 — but the sounds have character: the kick thuds rather than punches, the snare has a dry papery quality, the hats have vinyl sheen. Gentle swing (52–54%) gives a drowsy, nodding quality.',
            'emotion': 'Emotion: Nostalgic, calm, meditative. The lo-fi aesthetic communicates authenticity through imperfection — the warmth of something that has been played, loved, and degraded by time.',
            'whenUse': 'When to use: Study beats, ambient hip-hop, lo-fi playlists, tracks designed for listening rather than movement. Works with jazz-influenced melodies, soft piano chords, muted guitar. 70–90 BPM.',
            'whenNot': 'When not to use: Trap, dance, anything that needs energy and modern production gloss. The deliberately degraded aesthetic reads as low-budget if the genre context doesn\'t call for it.',
            'build': 'Build: Sample-based: chop a drum break (Amen, Think, Funky Drummer) and use only the kick and snare hits. Or use a drum sample pack with "vintage" or "vinyl" samples. Process: Waves J37 tape saturation (high drive, 50% wet) → Waves SSL G-Channel (low-pass shelf at 10kHz, −3dB) → Ableton Vinyl Distortion (Crackle and Warp at low levels for noise floor). Apply MPC 52% swing to the MIDI clip. Add a subtle room reverb (Ableton Reverb, short room, 15% wet) baked in to the samples before bouncing.',
            'signalChain': 'Signal chain: Drums into Waves J37 (tape saturation, high input) → Waves SSL G-Channel (cut above 10kHz) → Waves L2 (soft clip the peaks so nothing is too transient) → Ableton Vinyl Distortion (noise only, very low). Bus: gentle Waves CLA-2A compression (barely compressing, just adding the LA-2A character).',
            'keyTip': 'Key tip: The most important lo-fi technique is what you remove, not what you add. Cut the top end. Add subtle noise. Pull the transients back with light compression. The lo-fi sound is not adding distortion — it\'s removing clarity. Start with a clean drum sound and degrade it one step at a time, checking after each step.',
            'references': 'References: Nujabes (Feather, Aruarian Dance), J Dilla (Donuts — listen to the drum texture), Knxwledge, Sango, L\'Orange. The Lofi Girl YouTube channel as a reference for the aesthetic and BPM range.',
        },
        'meta': {'tag': 'Lo-Fi'},
    },
    {
        'id': 'pop-hybrid',
        'type': 'style',
        'title': 'Modern Pop / Hybrid',
        'oneLiner': 'The commercial default. Programmed precision with live texture layers.',
        'filters': ['pop', 'electronic', 'organic'],
        'sections': {
            'sound': 'Sound: A core drum pattern that is programmed and quantized perfectly, with live texture layers (room mic, overheads, or live snare sample) added on top for warmth and human feel. The programmed layer provides consistency and clarity; the live layer provides character and dimension. The combination reads as both polished and alive. Snare on 2 and 4, kick variations, 16th-note hats at mixed velocity.',
            'emotion': 'Emotion: Confident, professional, radio-ready. The drums support the vocal without drawing attention to themselves. They work.',
            'whenUse': 'When to use: Pop, indie-pop, singer-songwriter-with-production, soft alternative. Billie Eilish, Olivia Rodrigo, Sabrina Carpenter territory. Any commercial context where the music needs to feel both modern and warm.',
            'whenNot': 'When not to use: Contexts that want a clear aesthetic statement — lo-fi wants obvious lo-fi drums, trap wants obvious trap drums. Hybrid works when the genre isn\'t making a strong aesthetic statement about its production style.',
            'build': 'Build: Layer 1 (programmed): quantized MIDI drum pattern in Ableton with clean, punchy one-shot samples. Layer 2 (texture): a room impulse response applied to the snare (short, 0.3–0.8 second room), or a live snare sample at low velocity mixed beneath the programmed snare. Add subtle hiss (Ableton Vinyl Distortion at 2%) to create a noise floor that ties the layers together. Sidechain subtle elements to the kick for sub-bass clarity.',
            'signalChain': 'Signal chain: Kick: Waves SSL G-Channel → Waves CLA-76 (fast, 4:1). Snare (programmed): Waves SSL → Waves CLA-76 (fast, 8:1). Snare room layer: Waves RVerb (small room, 0.4s decay) → mix at −12dB below the dry snare. Bus: Waves SSL G-Bus (2:1 glue, slow attack) → Waves H-EQ (subtle high shelf boost at 12kHz for air).',
            'keyTip': 'Key tip: The room layer on the snare is the single most effective tool for making programmed drums feel alive. The programmed snare gives you control; the room layer gives you dimension. The room layer should be inaudible when you solo it — you only notice it when it\'s removed. That\'s the correct blend.',
            'references': 'References: Finneas O\'Connell (all Billie Eilish production — programmed drums with heavy texture layering). Dan Nigro (Olivia Rodrigo — SOUR, GUTS). Amy Allen, Jon Bellion. Charlie Puth as an extreme example of precision-first programming.',
        },
        'meta': {'tag': 'Pop'},
    },
    {
        'id': 'minimal-space',
        'type': 'style',
        'title': 'Minimal / Sparse Percussion',
        'oneLiner': 'Space is the composition. Every hit is a decision.',
        'filters': ['electronic', 'organic', 'ambient'],
        'sections': {
            'sound': 'Sound: Percussion at the level of suggestion rather than structure. A single kick hit every 2 bars. A hand drum in the left channel. Finger snaps instead of a snare. The listener is always aware of the space between sounds — that space carries as much emotional weight as the sounds themselves. There is no groove grid; there is only intention.',
            'emotion': 'Emotion: Contemplative, intimate, unresolved. Creates an expectation of more that never arrives — the absence is felt as much as the presence. Used to draw the listener into vulnerability.',
            'whenUse': 'When to use: Introspective ballads, ambient-influenced pop, tracks where the vocal is carrying everything and rhythm should not compete. Bon Iver, Sufjan Stevens, James Blake, early Lorde.',
            'whenNot': 'When not to use: Any context that needs groove, energy, or dance-floor function. If the listener needs to move, sparse percussion will feel empty rather than intentional.',
            'build': 'Build: Start with nothing. Add one sound at a time and ask whether it contributes or clutters. Common elements: a single kick or low tom hit on bar 1 (or every 2 bars). A rim shot or finger snap where a snare would be — but not on every bar. A shaker or tambourine at 1/8 note intervals, very quiet, just underneath the arrangement. Reverb as texture: a long reverb tail (2–4 seconds) on a single hit becomes a rhythmic element — the decay creates motion.',
            'signalChain': 'Signal chain: Each percussion element treated individually. Kick: minimal processing — HPF, gentle compression, done. Room/reverb: Waves RVerb (long plate, 2–4s decay) on a send, used as a textural element rather than a "drum reverb." Percussion layers: Waves SSL E-Channel (HPF high — kick at 60Hz, snare-type hits at 200Hz) to keep the low end uncluttered.',
            'keyTip': 'Key tip: Reverb tail length becomes a rhythmic element in sparse production. A snare hit with a 2-second decay at 90 BPM lands between bars 1 and 2, creating a phantom rhythmic event. This is intentional, not accidental. Tune your reverb decay to the tempo: at 90 BPM, a 1-beat reverb tail = 667ms. At 70 BPM = 857ms. Make the tail a musical length.',
            'references': 'References: Bon Iver (For Emma, Forever Ago — Justin Vernon, recorded alone in a cabin). James Blake (self-titled, Overgrown — James Blake). Sufjan Stevens (Carrie & Lowell). Lorde (Pure Heroine, produced by Joel Little — many tracks have almost no drums).',
        },
        'meta': {'tag': 'Minimal'},
    },
]

DRUMS_TECHNIQUES = [
    {
        'id': 'kick-layering',
        'type': 'technique',
        'title': 'Kick Drum Layering',
        'oneLiner': 'Stack multiple samples to build a full-range kick: sub, body, click.',
        'filters': ['sound-design', 'mixing'],
        'sections': {
            'whatItDoes': 'A single kick sample rarely covers the full frequency range needed. Sub layer (40–80Hz): the weight felt in the chest. Body layer (80–200Hz): the "thud" heard on consumer speakers. Click layer (2–5kHz): the attack transient that cuts through dense mixes on small speakers. Three separate layers, each doing one job.',
            'whenUse': 'When to use: Any time your kick feels weak on small speakers, lacks sub on a system, or doesn\'t cut through a dense arrangement. Nearly all commercial pop and hip-hop uses layered kicks — the question is whether it\'s one sample that covers all ranges or explicit layers.',
            'howToDo': 'How to do it: Layer 1 (sub): a pure sine or 808 kick, pitched to the root note of the song. Low-pass at 100Hz. Keep mono. Layer 2 (body): a punchy kick sample, HPF at 60Hz, LPF at 400Hz. Layer 3 (click): a transient sample (can be a drumstick click, a wood block, or the top end of a different kick), HPF at 1kHz. Tune each layer to the same root note. Balance: sub at 0dB, body at −3dB to −6dB, click at −6dB to −12dB. Check the combination on laptop speakers — the click and body do the work there.',
            'wavesPlugins': 'Waves plugins: Waves RBass on the body layer (adds sub-harmonic energy synthetically). Waves Transient Master on the click layer (enhance attack, reduce sustain). Waves C6 on the kick bus to control the crossover between layers.',
            'keyTip': 'Key tip: Tune the sub layer to the root note of the song — or at minimum check that it doesn\'t clash. An A-tuned sub layer over an Eb chord creates beating that sounds wrong even if you can\'t name why. Tune every kick sub layer before doing anything else.',
        },
        'meta': {'category': 'Sound Design'},
    },
    {
        'id': 'snare-layering',
        'type': 'technique',
        'title': 'Snare & Clap Layering',
        'oneLiner': 'Stack a snare body, a clap crack, and a noise layer for full presence.',
        'filters': ['sound-design', 'mixing'],
        'sections': {
            'whatItDoes': 'Like kick layering, a single snare sample rarely has everything. Body layer (200–400Hz): warmth and thud. Crack layer (1–4kHz): the sharp attack. Noise/room layer: sustain and space. The combination of all three creates a snare that works at every frequency and in every context.',
            'whenUse': 'When to use: When a snare sounds thin in the mix, lacks crack, or disappears behind guitars and synths. When you want a snare with a specific character that no single sample achieves.',
            'howToDo': 'How to do it: Layer 1 (body): a snare sample with a full 200–400Hz response. Layer 2 (crack): a clap or rimshot sample, HPF at 800Hz. Layer 3 (noise): a very short white noise sample (50–100ms) through a gate, blended at −12dB to −18dB — it adds a papery, organic quality without being audible as noise. Tune all layers to the same implied pitch (snares have a pitch around E2–A2). Apply the same reverb to all three layers — this is what makes them sound like one instrument.',
            'wavesPlugins': 'Waves plugins: Waves CLA-76 on each layer (fast attack, 8:1, for consistency). Waves RVerb on a send shared by all snare layers. Waves OneKnob Driver on the clap layer at low drive (5–10%) for density.',
            'keyTip': 'Key tip: The noise layer is the secret of most classic snare sounds. Analog snare drums have noise built in (the wires/snares are vibrating against a membrane). Synthetic snares sound flat without it. A 50ms white noise sample at −15dB on the snare layer adds this texture back.',
        },
        'meta': {'category': 'Sound Design'},
    },
    {
        'id': 'drum-tuning',
        'type': 'technique',
        'title': 'Drum Tuning',
        'oneLiner': 'Pitch your kick and toms to the key of the song. Wrong tuning causes beating.',
        'filters': ['sound-design', 'mixing'],
        'sections': {
            'whatItDoes': 'Drums have pitch — especially kicks and toms. A kick tuned to A2 (110Hz) against a song in Eb creates harmonic beating that makes the mix feel "off" even to listeners who can\'t identify why. Tuning drums to the root (or fifth) of the song eliminates this tension and makes the drums feel like they belong musically.',
            'whenUse': 'When to use: Always — for kick and bass alignment. Especially critical when the kick sub layer and the bass guitar/synth both occupy 60–100Hz. A half-step clash at those frequencies causes significant phase beating in the low end.',
            'howToDo': 'How to do it: Load the kick sample in Ableton\'s Simpler or a similar sampler. Use a spectrum analyser (Ableton\'s built-in, or Waves PAZ Analyzer) to find the fundamental frequency of the kick (the lowest visible peak). Tune the pitch until that fundamental is at the root note of the song, or the fifth, or the octave. For example: song in A minor → tune the kick sub to A (55Hz, 110Hz, or 220Hz depending on the kick). Toms: same process, but spread across the root, third, and fifth for a triad of tom pitches.',
            'wavesPlugins': 'Waves plugins: Waves Tune Real-Time (can be placed on a drum sample channel to tune the pitch in real time). Waves PAZ Analyzer (to identify the fundamental frequency before tuning).',
            'keyTip': 'Key tip: You don\'t need to match the root exactly — the fifth also works and can sound more natural for kicks (a fifth up from A = E). The rule is: avoid half-step clashes at the sub-bass frequency. An A kick against a Bb bass is the worst case. An A kick against an E bass is consonant and musical.',
        },
        'meta': {'category': 'Sound Design'},
    },
    {
        'id': 'ghost-notes',
        'type': 'technique',
        'title': 'Ghost Notes',
        'oneLiner': 'Quiet snare hits between the main hits. Felt, not heard. The difference between a groove and a grid.',
        'filters': ['midi', 'groove'],
        'context': {
            'tempo': ['under 80', '80-100'],
            'feel': ['laid back', 'behind', 'heavy'],
            'tone': ['warm', 'soulful', 'intimate'],
        },
        'sections': {
            'whatItDoes': 'Ghost notes are snare drum hits programmed at very low velocity (15–40 out of 127). They don\'t register as individual snare hits — the listener feels them as rhythmic texture, a low-level conversation underneath the main hits. They\'re the reason neo-soul and funk patterns feel alive when isolated snare-on-2-and-4 patterns don\'t.',
            'whenUse': 'When to use: R&B, neo-soul, funk, any pattern where you want a live drumming vocabulary. Most effective at 70–100 BPM where there\'s room between the main hits for ghost notes to breathe.',
            'howToDo': 'How to do it: In the MIDI piano roll, draw snare hits at velocity 15–35 on the 16th-note positions around your main snare hits (which are at 100–110). Typical ghost pattern: main snare at position 2 (velocity 105) → ghost at the "e" of beat 1 (velocity 25) → ghost at the "ah" of beat 2 (velocity 20) → main snare at position 4 (velocity 100) → ghost at the "e" of beat 3 (velocity 30). The pattern builds and releases.',
            'wavesPlugins': 'Waves plugins: No specific plugin. Velocity-sensitive drum sampler required. The ghost notes should use the same snare sample as the main hits — velocity differences create the dynamic contrast, not different samples.',
            'keyTip': 'Key tip: Ghost notes must be significantly quieter than you think. If you can hear them as individual snare hits, they\'re too loud. Target −15 to −18dB below the main snare. The correct level is: when you mute the ghost notes, the groove feels slightly less alive. That\'s the test.',
        },
        'meta': {'category': 'MIDI / Groove'},
    },
    {
        'id': 'groove-quantize',
        'type': 'technique',
        'title': 'Groove Quantization',
        'oneLiner': 'Pull notes off the perfect grid. Controlled imperfection creates feel.',
        'filters': ['midi', 'groove'],
        'context': {
            'tempo': ['under 80', '80-100'],
            'feel': ['laid back', 'behind'],
            'tone': ['warm', 'soulful'],
        },
        'sections': {
            'whatItDoes': 'Perfect quantization (100% to the grid) removes all timing variation and creates a mechanical, inhuman feel. Groove quantization shifts notes slightly off the grid in a controlled way — the same small delay applied consistently, which creates a groove template. MPC swing shifts every other 16th note slightly late, creating the loping boom-bap feel. Behind-the-beat feel shifts all notes slightly after the grid, creating the laid-back R&B quality.',
            'whenUse': 'When to use: Hip-hop (boom bap especially), R&B, soul, jazz-influenced production. Any pattern that currently feels stiff or robotic. Start with 100% quantization to get the pattern right, then apply groove to add feel.',
            'howToDo': 'How to do it: Ableton Groove Pool: drag a groove template (MPC 16 Swing, Human Feel, etc.) onto a MIDI clip. Adjust the Amount slider — start at 50% and A/B against the fully quantized version. Or: manually offset certain hits by 1–3ms in the MIDI piano roll. The kick landing 2ms late creates laid-back feel. The snare landing 1ms early creates urgency. Small numbers have big perceptual impact.',
            'wavesPlugins': 'Waves plugins: No specific plugin — this is a MIDI editing and DAW technique.',
            'keyTip': 'Key tip: Don\'t apply groove to everything equally. The kick and snare can be slightly late (laid back) while the hi-hats stay tighter. Real drummers play the big hits slightly behind the beat (weight) while the subdivision stays more consistent. That contrast — relaxed pulse, consistent subdivision — is the live drumming feel.',
        },
        'meta': {'category': 'MIDI / Groove'},
    },
    {
        'id': 'parallel-drums',
        'type': 'technique',
        'title': 'Parallel Compression (New York Style)',
        'oneLiner': 'Crush a parallel drum bus, blend back in. Density without killing dynamics.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'The main drum bus retains natural dynamics and punch. A parallel duplicate is compressed heavily (8:1 or higher, fast attack, significant GR) to create a dense, sustain-forward version. Blending 15–25% of the parallel signal into the main bus adds weight and thickness without squashing the transients — the snare still cracks, the kick still punches.',
            'whenUse': 'When to use: Live drums that are dynamic and punchy but disappear in a dense mix. Any drum bus that needs more aggression. Classic for rock, R&B, and pop mixing.',
            'howToDo': 'How to do it: Create a send from the main drum bus to a parallel return channel. On the return: Waves CLA-76 at 8:1 or higher, attack full left (fastest), release fast. Drive the gain reduction into 8–12dB territory. HPF the parallel channel at 80Hz (prevents sub smearing). Blend the return at 15–25%. The kick and snare on the main bus still punch; the parallel adds the density and sustain that fills out the mix.',
            'wavesPlugins': 'Waves plugins: Waves CLA-76 (the classic New York parallel compression compressor), Waves SSL G-Channel (for a smoother parallel character), Waves API 2500 (punchy, aggressive parallel option).',
            'keyTip': 'Key tip: The parallel bus can also include saturation — Waves OneKnob Driver at 20–30% on the parallel return adds harmonic density. The combination of heavy compression + saturation on the parallel creates a drum sound that feels "analogue-thick" even when the source is entirely digital.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'transient-shaping',
        'type': 'technique',
        'title': 'Transient Shaping',
        'oneLiner': 'Control attack and sustain independently. Make drums punchier or rounder without touching EQ.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'A transient shaper controls the attack (the initial spike) and sustain (the decay) of a drum hit separately. Increase attack: makes the drum punchier and more forward. Decrease attack: rounds off the transient for a more compressed sound. Increase sustain: adds room/bloom after the hit. Decrease sustain: cuts the tail, makes the drum tighter and drier. None of this affects frequency — it\'s purely dynamic shaping.',
            'whenUse': 'When to use: Kick that\'s losing its click in a dense mix — increase attack. Snare that sounds too "clicky" — decrease attack. Any drum that sounds too roomy — decrease sustain. Hi-hats with too much ring — decrease sustain.',
            'howToDo': 'How to do it: Waves Transient Master: Attack knob (positive = more punch, negative = softer) and Sustain knob (positive = more bloom, negative = tighter). Insert on individual drum channels, not the bus — you want different settings per drum. Kick: Attack +2, Sustain −3 (tight and punchy). Snare: Attack +1, Sustain 0 to +1 (crack with some room). Hi-hats: Sustain −2 (cut the ring).',
            'wavesPlugins': 'Waves plugins: Waves Transient Master (the dedicated tool). Waves SSL G-Channel (Attack/Release controls do similar work via compression).',
            'keyTip': 'Key tip: Transient shaping and compression are different tools for different problems. Compression responds to level (loud signals get compressed). Transient shaping responds to shape (the attack spike gets shaped regardless of level). Use transient shaping when you want to change the feel of a hit without changing its level.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'reverb-room-design',
        'type': 'technique',
        'title': 'Reverb & Room Design',
        'oneLiner': 'The reverb tells the listener where the drums are. Choose deliberately.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'Reverb places drums in a virtual space. Short room reverb (0.3–0.6s): drums in a small studio, intimate and close. Medium hall (0.8–1.5s): arena or concert hall, bigger and more cinematic. Long plate (1.5–3s): classic pop and R&B snare tail, grand and emotional. No reverb (dry): electronic/trap aesthetic, drums feel present and modern.',
            'whenUse': 'When to use: Every production decision about reverb is a statement about space. Trap = no reverb (dry is the aesthetic). Boom bap = short room on snare. Neo-soul = medium room, shared across the whole kit. Ballad = long plate on the snare for emotion.',
            'howToDo': 'How to do it: Use sends rather than inserts — multiple drums sharing the same reverb send unifies them as a kit. Snare send level: higher (more reverb). Kick send level: lower (too much kick reverb clouds the low end). Hi-hat send level: usually zero. Waves RVerb: Room type affects character — "Hall" sounds cinematic, "Room" sounds intimate, "Plate" sounds classic pop. Pre-delay (30–50ms): creates separation between the dry hit and the reverb tail, maintaining punch while adding space.',
            'wavesPlugins': 'Waves plugins: Waves RVerb (versatile, clean), Waves H-Reverb (for more unusual spaces), Waves IR-1 (convolution reverb for real room impulses), Waves Abbey Road Plates (classic plate reverb sound).',
            'keyTip': 'Key tip: Pre-delay is the most important reverb parameter for drums. A 30–50ms pre-delay means the reverb tail starts 30ms after the dry hit — this preserves the transient punch while adding space. Without pre-delay, the reverb blurs the attack. With it, you can have large reverb tails and still hear every hit clearly.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'hi-hat-technique',
        'type': 'technique',
        'title': 'Hi-Hat Feel & Programming',
        'oneLiner': 'Velocity variation and micro-timing in hi-hats is where groove lives.',
        'filters': ['midi', 'groove'],
        'sections': {
            'whatItDoes': 'Hi-hats are the most expressive element of a drum pattern — they carry groove, feel, and rhythmic tension. A hi-hat pattern with all notes at the same velocity feels robotic. The same pattern with intentional velocity variation (accents, ghosts, swells) feels human. Open hi-hats (played with the foot slightly raised) ring longer and add lift; closed hats are tight and driving.',
            'whenUse': 'When to use: All drum programming. The hi-hat is where genre identity and groove identity are most clearly expressed — trap hi-hats are different from boom bap hi-hats which are different from house hi-hats, mainly in their velocity patterns and open/closed relationships.',
            'howToDo': 'How to do it: For trap: 16th-note grid, velocity sweep from 25 to 110 over groups of 4–8 notes (crescendo to a snare hit). Open hat accent on phrase endings. For boom bap: swung 16ths, accent the on-beat hat (velocity 90), ghost the off-beat (velocity 50–60). For neo-soul: shuffle pattern (long-short 8ths), accents on the "and" beats. For house: straight 8ths, all velocity 80–90, open hat on the "and" of beat 2.',
            'wavesPlugins': 'Waves plugins: No specific plugin — this is MIDI programming. A velocity-sensitive sampler (Ableton Drum Rack, NI Battery) is required.',
            'keyTip': 'Key tip: Open and closed hi-hat notes need to voice-steal each other (the same note channel in MIDI). If your open hat doesn\'t cut off when the closed hat hits, they layer on top of each other and sound unnatural. Check your drum plugin\'s hi-hat choke settings — the open hat should be "choked" by the closed hat note.',
        },
        'meta': {'category': 'MIDI / Groove'},
    },
    {
        'id': 'sample-chopping',
        'type': 'technique',
        'title': 'Sample Chopping / Breakbeat Manipulation',
        'oneLiner': 'Cut a drum loop into individual hits and reassemble. The foundation of hip-hop production.',
        'filters': ['sound-design', 'hip-hop'],
        'sections': {
            'whatItDoes': 'Take a recorded drum loop (a "break"), slice it into individual drum hits (kick, snare, hat), and reassemble them in a new pattern. The original loop carries performance character — natural velocity variation, room sound, the feel of a live drummer — but you now control the pattern. This is the Akai MPC approach that created hip-hop drum production.',
            'whenUse': 'When to use: Hip-hop (boom bap especially), lo-fi, any context where you want live drum texture without recording a live drummer.',
            'howToDo': 'How to do it: In Ableton: drag a drum break audio file into the Arrangement. Use Warp markers to identify the transients. Slice to MIDI (right-click → Slice to New MIDI Track). Each slice becomes a pad. Draw a new MIDI pattern using the slices — kick from slice 1, snare from slice 4, hat from slice 3. Apply swing. This is the core MPC workflow recreated in software. Key breaks: Amen (NWA, DnB), Think (James Brown, boom bap), Funky Drummer (James Brown, the most sampled break in history).',
            'wavesPlugins': 'Waves plugins: Waves J37 Tape on the reassembled pattern for vintage warmth. Waves SSL G-Channel on the break channel for EQ before slicing.',
            'keyTip': 'Key tip: Pitch-shift individual slices before reassembling them. The kick from the break pitched down a tone, the snare pitched up a semitone — you get a new instrument with the character of the original break. This is one of the primary ways hip-hop producers create "signature" drum sounds from common source material.',
        },
        'meta': {'category': 'Sound Design'},
    },
    {
        'id': 'swing-humanize',
        'type': 'technique',
        'title': 'Swing & Humanization',
        'oneLiner': 'MPC swing, micro-timing offsets, velocity randomization. The path from grid to groove.',
        'filters': ['midi', 'groove'],
        'sections': {
            'whatItDoes': 'Swing shifts alternate 16th notes slightly later than the grid, creating a loping, rhythmic push-pull. Humanization adds small random variations in timing (±5–15ms) and velocity (±10 velocity units) that simulate the natural inconsistency of human performance. Together these take a pattern from mechanical to musical.',
            'whenUse': 'When to use: Any programmed drum pattern that feels stiff. Hip-hop, R&B, soul, lo-fi. Even electronic and pop patterns benefit from subtle humanization (velocity variation at minimum).',
            'howToDo': 'How to do it: Swing: Ableton Groove Pool → MPC 16 Swing 54 template applied at 60–80% Amount. Or: select every other 16th note in the piano roll and nudge them 10–15ms later manually. Humanization: Ableton MIDI Effect → Velocity → set Random to 10–15 (adds ±10 velocity variation per note). For timing humanization: Ableton MIDI Effect → Random (time) at very small values (5–10ms). Or draw manual velocity variation rather than using randomization — intentional variation is more musical than random.',
            'wavesPlugins': 'Waves plugins: No specific plugin.',
            'keyTip': 'Key tip: Intentional velocity variation is better than randomized velocity variation. Randomization creates statistically even distribution — real drumming creates patterned variation (beat 1 louder, ghost notes quieter, crescendo into the snare). Draw your velocity variation deliberately. Think of it as a second performance layer on top of the pitch/timing layer.',
        },
        'meta': {'category': 'MIDI / Groove'},
    },
    {
        'id': 'drum-compression',
        'type': 'technique',
        'title': 'Drum Compression Styles',
        'oneLiner': '1176, LA-2A, VCA, optical — each compressor has a sound. Know what you\'re reaching for.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'Different compressor circuit types respond differently to drum transients, creating distinct sonic characters. Fast VCA (1176-style): catches transients quickly, adds punch and aggression. Slow optical (LA-2A-style): responds to program level, adds warmth and "program-dependent" compression. VCA bus (SSL G-Bus-style): glues multiple elements together, adds forward motion (the "pumping" from the mix bus). Knowing which to reach for is a core mixing skill.',
            'whenUse': 'When to use: 1176 (Waves CLA-76) on individual drums for punch and control — kick, snare. LA-2A (Waves CLA-2A) on room mics or overheads for warmth. SSL G-Bus (Waves SSL G-Bus Compressor) on the drum bus for glue. API 2500 (Waves API 2500) on the drum bus for a punchier, forward-leaning character.',
            'howToDo': 'How to do it: Kick: CLA-76, ratio 4:1, attack fast, release fast. 4–6dB GR. Snare: CLA-76, ratio 8:1, attack fast, release fast. 6–8dB GR. Overheads: CLA-2A, program-dependent. Just touching the GR needle. Drum bus: SSL G-Bus, ratio 2:1, attack slow (60ms — lets transients through), release auto. 2–4dB GR. This is the English mix bus compression sound — cohesive, musical, forward.',
            'wavesPlugins': 'Waves plugins: Waves CLA-76 (1176 emulation), Waves CLA-2A (LA-2A emulation), Waves SSL G-Bus Compressor, Waves API 2500, Waves dbx 160.',
            'keyTip': 'Key tip: Slow attack on the drum bus compressor is counterintuitive but critical. A fast-attack bus compressor catches the kick and snare transients and squashes them — the drums lose punch. A slow attack (40–80ms) lets the transients pass through uncompressed before the compressor engages — you get glue and density without losing impact.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'saturation-bus',
        'type': 'technique',
        'title': 'Bus Saturation & Glue',
        'oneLiner': 'Saturation on the drum bus adds harmonic density and makes disparate samples cohere.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'When drum sounds come from multiple sources (different sample packs, different years, different rooms), they can sound disconnected in the mix. Bus saturation — light harmonic distortion applied to the whole drum bus — adds a shared harmonic fingerprint that makes them sound like they were recorded in the same room. It also adds the "analogue warmth" character that digital drums often lack.',
            'whenUse': 'When to use: Any drum bus with samples from multiple sources. Sample-based hip-hop, modern pop with hybrid drums, any situation where drums sound disconnected or "digital." Even subtle saturation (just audible) makes a significant difference.',
            'howToDo': 'How to do it: Waves J37 Tape Saturation on the drum bus: Input Level to taste (more input = more saturation), Output Level to compensate for added gain, Speed at 7.5 ips for the warmest character. Start with the drive very low — just enough that you can hear it if you flip between bypassed and active. Or: Waves OneKnob Driver at 10–15% on the drum bus for a simpler approach. Parallel saturation: send the drum bus to a saturation return and blend 10–20% — this adds the character without affecting the transient impact.',
            'wavesPlugins': 'Waves plugins: Waves J37 Tape Saturation (the most musically useful), Waves OneKnob Driver (simple), Waves Kramer Master Tape, Waves Abbey Road Saturator.',
            'keyTip': 'Key tip: Saturation before compression on the drum bus is different from saturation after. Before compression: the saturation changes the transient shapes, which the compressor then responds to — the result is unpredictable but often more musical. After compression: the saturation adds harmonic density to an already-controlled signal — cleaner and more predictable. Try both.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'sidechain-drums',
        'type': 'technique',
        'title': 'Sidechain from Kick',
        'oneLiner': 'The kick controls other elements in the mix. Creates rhythmic movement and space.',
        'filters': ['mixing', 'processing'],
        'sections': {
            'whatItDoes': 'The kick drum output is used as a trigger signal to compress (or duck) other elements in the mix — bass, pads, synths. Each kick hit causes those elements to briefly lose level, then recover. The result: the kick has space to punch through (nothing is competing at the moment of impact) and the recovery creates rhythmic motion in the mix.',
            'whenUse': 'When to use: Dance music (the sidechain pump IS the genre in house and electropop). Subtle sidechain on bass in any pop/hip-hop production — the kick and bass need different moments. Any mix where the kick and bass are fighting for the same space.',
            'howToDo': 'How to do it: Ableton Compressor on the bass or pad channel → Sidechain button → select the kick as the Audio From input. Ratio 4:1–8:1 for subtle, 10:1+ for audible pumping. Attack 3–10ms. Release timed to the tempo: at 120 BPM, 1 beat = 500ms, 1/2 beat = 250ms. For subtle: aim for 2–4dB GR on each kick hit. For pumping: 6–10dB GR. HPF the sidechain signal at 100Hz so only the kick click (not the sub) triggers the compression.',
            'wavesPlugins': 'Waves plugins: Waves SSL G-Channel (has sidechain input), Waves C6 (frequency-specific sidechain — only the 60–100Hz band of the bass ducks, not the whole bass signal).',
            'keyTip': 'Key tip: Use frequency-specific sidechain (Waves C6 or F6 in dynamic mode) for subtle kick/bass separation. Instead of the whole bass ducking on every kick hit, only the sub-bass frequency band (60–100Hz) ducks — the rest of the bass is unaffected. The result is kick and bass no longer masking each other in the sub, without the pumping effect that overt sidechain creates.',
        },
        'meta': {'category': 'Mixing'},
    },
    {
        'id': 'overhead-perspective',
        'type': 'technique',
        'title': 'Overhead Perspective & Phase',
        'oneLiner': 'The overhead mics are the picture. The close mics are correction. Get this relationship right.',
        'filters': ['recording', 'mixing'],
        'sections': {
            'whatItDoes': 'In live drum recording (or when working with acoustic drum samples), the overhead microphones capture the whole kit as a balanced instrument. The close mics (kick, snare, tom) provide focus and punch. The most common mistake is treating the close mics as the primary signal and the overheads as "extra." Reversing this — making the overheads primary — produces drum sounds that are more natural, cohesive, and musical.',
            'whenUse': 'When to use: Any time working with recorded live drums or acoustic drum sample libraries that include room/overhead signals. Less relevant for purely electronic/sampled drums (though a room reverb send simulates the overhead effect).',
            'howToDo': 'How to do it: Mix session: bring overhead faders to 0dB. Listen — this is the starting picture. Now bring up the kick close mic until the kick has appropriate punch. Bring up the snare close mic until the crack feels right. Stop adding close mics when they start dominating over the overheads. The close mics are adding definition to a picture that already sounds like a kit. Phase check: in Logic or Ableton, zoom to the sample level and verify the kick waveform polarity on the close mic matches the kick on the overhead. If they\'re opposite, flip the close mic phase.',
            'wavesPlugins': 'Waves plugins: Waves InPhase (dedicated phase alignment tool for multi-mic drum tracks). Waves SSL E-Channel on each channel for HPF and tonal shaping.',
            'keyTip': 'Key tip: Phase alignment between the kick close mic and the overheads is the most important technical issue in drum mixing. If they\'re out of phase, the kick loses low end dramatically — the two signals cancel each other. Zoom to the sample level, look at the kick waveforms on both tracks, and manually nudge the close mic so the peaks align with the overhead peaks.',
        },
        'meta': {'category': 'Recording'},
    },
]

DRUMS_CHARACTER = [
    # Pair 1: Tight / Loose
    {
        'id': 'drum-tight',
        'type': 'character',
        'title': 'Tight Drums',
        'oneLiner': 'Grid-locked, quantized, on the beat. Every hit lands where it should.',
        'filters': [],
        'sections': {
            'description': 'Description: Every drum hit lands exactly on the grid. No swing, no feel-based offset, no humanization. The drum pattern is a precision instrument — its purpose is rhythmic clarity and modern polish. Modern trap, house, and commercial pop production typically lives here.',
            'why': "Why you'd want it: Control and clarity. When the music around the drums is complex or harmonically rich, tight drums provide an unambiguous rhythmic foundation. Also: the aesthetic of tightness is a genre choice — trap and house both use tight drums as a style statement, not a limitation.",
            'how': 'How to get there: Quantize all drum MIDI to 100% at the relevant subdivision (16th notes usually). Avoid swing groove templates. Keep velocity variation intentional but not extreme. For samples: use transient shaping (Waves Transient Master) to give each hit a sharp attack that locks to the grid perceptually.',
            'reference': 'Reference: Travis Scott (programmed trap drums — the grid is intentional), Calvin Harris (four-on-the-floor house), Charlie Puth (extreme precision drumming as aesthetic).',
            'helper': "If you don't know: Tight is what programmed drums sound like by default. It's not a mistake — it's a choice. The question is whether it's the right choice for this music.",
        },
        'meta': {'pairId': 'drum-tight-loose', 'pole': 'left', 'poleName': 'Tight', 'group': 'Feel'},
    },
    {
        'id': 'drum-loose',
        'type': 'character',
        'title': 'Loose Drums',
        'oneLiner': 'Swinging, behind the beat, breathing. The drummer is a human being.',
        'filters': [],
        'sections': {
            'description': 'Description: Notes land slightly before or after the grid — deliberately, consistently, with intention. Swing shifts alternate 16th notes later. Behind-the-beat feel delays the whole pattern by 5–20ms. The loose drum pattern leans back, breathes, invites the listener to settle into the groove rather than ride it.',
            'why': "Why you'd want it: Warmth, humanity, groove. Loose drums signal that the music is about feel rather than precision. They invite a different listening posture — more passive, more embodied, less analytical.",
            'how': 'How to get there: Apply MPC-style swing to the MIDI clip (Ableton Groove Pool). Or offset the whole drum pattern 10–15ms late relative to the grid. Or manually nudge individual hits in the piano roll. The key: consistency. Random timing variation is not loose — it\'s sloppy. Intentional, patterned timing offset is loose.',
            'reference': 'Reference: J Dilla (the definitive loose hip-hop drummer). D\'Angelo Black Messiah (Questlove playing behind the beat). Amy Winehouse — Back to Black (the drums lurch back on every bar).',
            'helper': "If you don't know: Play your MIDI pattern. Then select all notes and nudge them 15ms to the right. Listen. That\'s the beginning of loose.",
        },
        'meta': {'pairId': 'drum-tight-loose', 'pole': 'right', 'poleName': 'Loose', 'group': 'Feel'},
    },
    # Pair 2: Punchy / Roomy
    {
        'id': 'drum-punchy',
        'type': 'character',
        'title': 'Punchy Drums',
        'oneLiner': 'Fast transients, short decays, forward and present in the mix.',
        'filters': [],
        'sections': {
            'description': 'Description: The attack of each drum hit is sharp and immediate. Decays are short — the sound doesn\'t linger. The drums are perceived as being "in front of" the other elements. Achieved through fast compression, transient enhancement, and short reverb (or none).',
            'why': "Why you'd want it: Presence and impact. Punchy drums cut through dense arrangements, work well for rhythm-forward music, and create the sense that the drums are driving the track rather than supporting it.",
            'how': 'How to get there: Compress with fast attack (Waves CLA-76, fastest setting). Use transient shaping to enhance the attack and reduce sustain (Waves Transient Master: Attack +2, Sustain −2). Keep reverb short (0.2–0.4s room). Boost 3–5kHz slightly for click and presence.',
            'reference': 'Reference: Phil Collins (In The Air Tonight — dry, punchy, close drum sound). Death Cab for Cutie (Narrow Stairs — Michael Lerner\'s drums, punchy and forward). Modern hip-hop kicks.',
            'helper': "If you don't know: Punchy = close. The drums sound like they're in the room with you, right in front of your face.",
        },
        'meta': {'pairId': 'drum-punchy-roomy', 'pole': 'left', 'poleName': 'Punchy', 'group': 'Space'},
    },
    {
        'id': 'drum-roomy',
        'type': 'character',
        'title': 'Roomy Drums',
        'oneLiner': 'Long reverb tails, the kit sounds like it\'s in a real space.',
        'filters': [],
        'sections': {
            'description': 'Description: The drum sounds are surrounded by reverb that places them in a real (or imagined) room, hall, or chamber. The decay of each hit extends into the space between notes. Roomy drums feel cinematic, grand, and spatially immersive. The listener perceives distance between themselves and the kit.',
            'why': "Why you'd want it: Atmosphere, cinema, grandeur. Roomy drums work when the music is trying to create a sense of place or scale — an arena, a cathedral, a canyon. Also useful for making sparse patterns feel full (the reverb tail fills the space between hits).",
            'how': 'How to get there: Waves RVerb on a send: Hall or Room type, decay 0.8–2s, pre-delay 30ms (to preserve punch). Send the snare at a high level, kick at a low level (too much kick reverb muddies the low end), hi-hats at zero. Longer reverb = more distance. Shorter pre-delay = more depth (the reverb overlaps more with the dry sound).',
            'reference': 'Reference: Led Zeppelin — When the Levee Breaks (recorded in the stairwell of Headley Grange — the most famous drum room sound ever). Phil Spector Wall of Sound. Modern: The National (Bryan Devendorf\'s drums in large room recordings).',
            'helper': "If you don't know: Roomy = distant. The drums sound like they're at the back of a large room and you're listening from the front.",
        },
        'meta': {'pairId': 'drum-punchy-roomy', 'pole': 'right', 'poleName': 'Roomy', 'group': 'Space'},
    },
    # Pair 3: Sparse / Dense
    {
        'id': 'drum-sparse',
        'type': 'character',
        'title': 'Sparse Pattern',
        'oneLiner': 'Few hits, maximum space. Every hit is a decision.',
        'filters': [],
        'sections': {
            'description': 'Description: The pattern has few notes. Kick once per bar or less. Snare on 2 and 4 only, no fills. Hi-hats minimal or absent. The space between hits is the composition as much as the hits themselves.',
            'why': "Why you'd want it: Intimacy, focus on the vocal, emotional space. When the music is asking the listener to feel something rather than move, sparse drums get out of the way. Also effective as contrast — a sparse verse makes a dense chorus land harder.",
            'how': 'How to get there: Start with only a snare on 2 and 4. Ask: does the kick add anything essential? If not, remove it. Ask: do the hats add anything essential? If not, remove them. Repeat for every element. Stop removing when the pattern starts to feel empty rather than intentional.',
            'reference': 'Reference: James Blake (self-titled — often only a snare hit every 2 bars). Bon Iver (For Emma — minimal percussion). Lorde (Royals — the kick and snare pattern is almost childlike in its simplicity; the song is all about the space).',
            'helper': "If you don't know: Remove one element at a time from your current drum pattern. Keep removing until something feels missing. Then add that one thing back. That's your sparse version.",
        },
        'meta': {'pairId': 'drum-sparse-dense', 'pole': 'left', 'poleName': 'Sparse', 'group': 'Density'},
    },
    {
        'id': 'drum-dense',
        'type': 'character',
        'title': 'Dense Pattern',
        'oneLiner': 'Fills, ghost notes, constant motion. The drums are always doing something.',
        'filters': [],
        'sections': {
            'description': 'Description: The pattern is full — ghost notes, hat variations, subtle fills, snare rolls, multiple percussion layers. The drum part has musical complexity. Not busy for its own sake, but where every added element contributes to the feel and energy of the track.',
            'why': "Why you'd want it: Energy, complexity, sophistication. Dense drum parts signal production investment and rhythmic intelligence. They\'re engaging to listen to closely and create a sense of controlled chaos — lots of activity underneath a clear groove.",
            'how': 'How to get there: Start with a simple pattern. Add ghost notes between main snare hits. Add hi-hat fills at phrase endings (last 2 bars of 8). Add a subtle kick variation (a 16th note early or late on beat 3). Each addition should increase energy without disturbing the fundamental pulse. The goal: more notes, same groove.',
            'reference': 'Reference: Questlove (The Roots — incredibly dense patterns underneath the groove). Anderson .Paak (drums and production simultaneously). Steely Dan recordings (complex drum patterns that never draw attention to themselves).',
            'helper': "If you don't know: Listen to J Dilla\'s Donuts. The patterns sound simple, but zoom in — there are ghost notes and subtle variations everywhere. Dense doesn't mean busy. It means full.",
        },
        'meta': {'pairId': 'drum-sparse-dense', 'pole': 'right', 'poleName': 'Dense', 'group': 'Density'},
    },
    # Pair 4: Electronic / Organic
    {
        'id': 'drum-electronic',
        'type': 'character',
        'title': 'Electronic Drums',
        'oneLiner': 'Synthesized or heavily processed samples. The drums are clearly not acoustic.',
        'filters': [],
        'sections': {
            'description': 'Description: Sounds that could not come from a physical drum kit — synthesized 808 kicks, claps made from noise generators, hi-hats that are white noise filtered through a resonant filter. Or: processed acoustic samples processed to the point where the origin is unrecognizable.',
            'why': "Why you'd want it: Genre identity, modern aesthetic, freedom from acoustic constraints. Electronic drums can do things no acoustic kit can — sustain forever, be tuned to exact notes, sidechain seamlessly, exist only in the sub-bass range.",
            'how': 'How to get there: Start with a synthesizer rather than a sample library. 808 kick: sine wave with pitch envelope (fast pitch drop from high to low). Clap: noise burst with short envelope and resonant filter. Hi-hat: white noise through bandpass filter (3–10kHz).',
            'reference': 'Reference: TR-808 and TR-909 drum machines (the source of all modern electronic drum vocabulary). Trap production. House music. Kraftwerk (Music Non Stop).',
            'helper': "If you don't know: Electronic drums have a specific vocabulary. They're not realistic — they're iconic. A TR-808 kick doesn't sound like a bass drum. It sounds like an 808.",
        },
        'meta': {'pairId': 'drum-electronic-organic', 'pole': 'left', 'poleName': 'Electronic', 'group': 'Source'},
    },
    {
        'id': 'drum-organic',
        'type': 'character',
        'title': 'Organic Drums',
        'oneLiner': 'Sounds like a human being played a physical kit in a room.',
        'filters': [],
        'sections': {
            'description': 'Description: Acoustic drum sounds with natural transients, room ambience, and human dynamic variation. Whether from live recording or high-quality acoustic sample libraries, organic drums have texture and imperfection built in — no two hits are identical.',
            'why': "Why you'd want it: Warmth, humanity, musicality. Organic drums signal that the production is rooted in the physical world. They work especially well with live instruments and natural vocals.",
            'how': 'How to get there: Use acoustic drum sample libraries (Superior Drummer, BFD, Abbey Road Drums). Enable round-robin alternation (each hit uses a different recorded sample) to avoid machine-gun repetition. Include room/overhead signal. Apply gentle swing and velocity variation. Avoid perfectly quantizing — leave 2–5ms of human timing variation.',
            'reference': 'Reference: Amy Winehouse Back to Black (Remi Kabaka Jr., Ronson production). The National (Bryan Devendorf). Radiohead (Phil Selway).',
            'helper': "If you don't know: Organic drums don't sound perfect. The imperfections are the point. Every hit is slightly different. The room is audible. The drummer breathes.",
        },
        'meta': {'pairId': 'drum-electronic-organic', 'pole': 'right', 'poleName': 'Organic', 'group': 'Source'},
    },
    # Pair 5: Hard / Soft
    {
        'id': 'drum-hard',
        'type': 'character',
        'title': 'Hard / Aggressive',
        'oneLiner': 'High velocity, sharp transients, maximum impact on every hit.',
        'filters': [],
        'sections': {
            'description': 'Description: The drums are played or programmed at high velocity. Every hit is an event. The snare cracks, the kick thuds, the hats are assertive. Compression is fast and aggressive (1176-style). The drums are a physical force in the mix.',
            'why': "Why you'd want it: Energy, aggression, impact. Hard drums work for genres where the music needs to feel powerful and intentional — rock, aggressive pop choruses, dark hip-hop. They command the listener\'s attention rather than supporting it.",
            'how': 'How to get there: Program all main hits (kick, snare) at 100–110 velocity. Fast attack compression (Waves CLA-76, fastest settings). Transient shaping: increase attack on kick and snare. Minimal reverb — hard drums are usually dry and present.',
            'reference': 'Reference: Nirvana (Dave Grohl — the hardest-hitting drummer of the 90s). Jack White productions. Billie Eilish choruses (the drums suddenly get hard and aggressive as a contrast to quiet verses).',
            'helper': "If you don't know: Hard = loud and sharp. The drums feel like they're hitting you.",
        },
        'meta': {'pairId': 'drum-hard-soft', 'pole': 'left', 'poleName': 'Hard', 'group': 'Impact'},
    },
    {
        'id': 'drum-soft',
        'type': 'character',
        'title': 'Soft / Delicate',
        'oneLiner': 'Low velocity, rounded transients, supporting the music from below.',
        'filters': [],
        'sections': {
            'description': 'Description: Drums played or programmed at lower velocity. The transients are rounded (slow attack compression or transient shaping). The dynamics serve the music — the drums are present but not dominant. Brushes instead of sticks. The drum pattern creates texture rather than impact.',
            'why': "Why you'd want it: Intimacy, delicacy, supporting a vulnerable vocal. Soft drums say: this music is asking you to feel, not move. They create space for the vocal and the emotion to be the loudest thing in the room.",
            'how': 'How to get there: Lower all drum velocities by 20–30 units from where they are. Use slow-attack compression to round off transients (Waves CLA-2A — program-dependent, slow). Add more reverb (the room sound softens the edge). Consider substituting brushed snare samples for stick samples. HPF hi-hats higher (10kHz+) to make them lighter.',
            'reference': 'Reference: Sufjan Stevens (brushed drums in intimate arrangements). Nick Drake (Danny Thompson — brushed double bass and soft percussion). Iron & Wine (Sam Beam productions).',
            'helper': "If you don't know: Soft = quiet and rounded. The drums feel like they're supporting the music from below, not driving it from above.",
        },
        'meta': {'pairId': 'drum-hard-soft', 'pole': 'right', 'poleName': 'Soft', 'group': 'Impact'},
    },
    # Pair 6: Bright / Dark
    {
        'id': 'drum-bright',
        'type': 'character',
        'title': 'Bright Drums',
        'oneLiner': 'High frequency content present. Cymbals shimmer, snare cracks, hats sizzle.',
        'filters': [],
        'sections': {
            'description': 'Description: The drum mix has significant high-frequency energy — cymbals shimmer and decay audibly, the snare crack extends into 8–12kHz, hi-hats are prominent and sibilant. Often achieved by preserving (or boosting) the overhead signal, which is naturally bright.',
            'why': "Why you'd want it: Air, energy, openness. Bright drums feel exciting and alive. They work well in energetic pop, indie rock, and any context where the mix needs high-frequency energy to feel complete.",
            'how': 'How to get there: Preserve overhead signal (or use room reverb with high-frequency extension). Gentle high shelf boost on the overhead channel at 10–12kHz (+1 to +2dB). Avoid over-HPF on the snare. Keep hi-hat samples that have natural shimmer.',
            'reference': 'Reference: The Beatles (Ringo Starr\'s kit, Abbey Road Studios — the overheads are the iconic bright character). Vampire Weekend (Rostam productions — bright, metallic cymbals).',
            'helper': "If you don't know: Bright drums sound like live drums in a good room. The cymbals are audible as musical instruments, not just rhythm markers.",
        },
        'meta': {'pairId': 'drum-bright-dark', 'pole': 'left', 'poleName': 'Bright', 'group': 'Frequency'},
    },
    {
        'id': 'drum-dark',
        'type': 'character',
        'title': 'Dark Drums',
        'oneLiner': 'High frequencies rolled off. Heavy, bodied, atmospheric.',
        'filters': [],
        'sections': {
            'description': 'Description: The drum mix has reduced high-frequency content. Cymbals are rolled off or absent. Hi-hats are filtered (low-pass at 8–10kHz) or replaced with darker sounds. The snare has body but not crack. The overall drum mix feels heavier and more atmospheric.',
            'why': "Why you'd want it: Weight, darkness, atmosphere. Dark drums work for introspective hip-hop, lo-fi, dark R&B, and any context where high-frequency energy would feel inappropriate. Also: dark drums give more room to the vocal and high-frequency instruments in the mix.",
            'how': 'How to get there: Low-pass filter the overhead or room channel at 8–10kHz. Use darker hi-hat samples (closed hats, not open hats with long tails). Cut 10kHz on the snare channel. Add warmth to the bus (Waves J37 tape saturation).',
            'reference': 'Reference: Nujabes (dark, warm hip-hop drums). Frank Ocean (Channel Orange — dark, filtered drums). The Weeknd (early mixtapes — heavily filtered, murky drum sounds).',
            'helper': "If you don't know: Dark drums sound like they\'re coming through a wall or a lo-fi tape deck. The high end is rolled off and the body and weight are left.",
        },
        'meta': {'pairId': 'drum-bright-dark', 'pole': 'right', 'poleName': 'Dark', 'group': 'Frequency'},
    },
    # Pair 7: Simple / Complex
    {
        'id': 'drum-simple',
        'type': 'character',
        'title': 'Simple Pattern',
        'oneLiner': 'The classic 4/4. Kick, snare, hat. Everything else is melody.',
        'filters': [],
        'sections': {
            'description': 'Description: Kick on 1 and 3. Snare on 2 and 4. Hi-hats on 8ths or 16ths. No fills, no ghost notes, no syncopation. The pattern is a clock — it marks time without adding rhythmic interest. Simple patterns get out of the way and let the melody, harmony, and vocal carry the music.',
            'why': "Why you'd want it: Clarity, support, restraint. Simple patterns are underrated. They work in almost any genre. They let the rest of the arrangement breathe. The best simple patterns are invisible — you don\'t notice the drums, only the music.",
            'how': 'How to get there: Program kick on beats 1 and 3, snare on 2 and 4, closed hi-hat on 8th notes. Add one small variation: a kick on the "ah" of beat 4 (anticipating beat 1) for forward motion. That\'s it. Resist adding anything else.',
            'reference': 'Reference: Most classic pop production. Phil Spector (the drums are intentionally simple beneath the Wall of Sound). Lorde (Simple But Effective — Joel Little productions often feature very basic drum patterns).',
            'helper': "If you don't know: The simplest useful drum pattern is: kick on 1, snare on 3. That's 2/4. Add a hat on every beat. That's a minimal 4/4. Everything else is elaboration.",
        },
        'meta': {'pairId': 'drum-simple-complex', 'pole': 'left', 'poleName': 'Simple', 'group': 'Complexity'},
    },
    {
        'id': 'drum-complex',
        'type': 'character',
        'title': 'Complex Pattern',
        'oneLiner': 'Syncopation, polyrhythm, fills, variations. The drums are a conversation.',
        'filters': [],
        'sections': {
            'description': 'Description: The pattern has rhythmic complexity — kicks land off the beat, syncopation pushes and pulls the groove, fills mark phrase boundaries, polyrhythmic hat patterns (3 over 4, 6 over 4) create tension against the main pulse. The drums are musically interesting as an isolated element.',
            'why': "Why you'd want it: Sophistication, engagement, musicality. Complex patterns reward close listening. They\'re appropriate when the music is trying to be rhythmically interesting — jazz, progressive pop, R&B with complex arrangements. Anderson .Paak makes drumming itself a performance.",
            'how': 'How to get there: Start with a simple pattern. Add one syncopated kick (landing on the "e" or "ah" of a beat). Add ghost notes between snare hits. Add a hi-hat pattern with an odd-number accent (3 hats over 4 beats). Add a fill in bar 4 of an 8-bar phrase. Each addition should feel earned, not arbitrary.',
            'reference': 'Reference: Anderson .Paak (drums as performance, not just timekeeping). Questlove (The Roots). Kendrick Lamar\'s To Pimp A Butterfly — the drum patterns are extraordinarily complex and specific to the arrangement.',
            'helper': "If you don't know: Complex doesn't mean random. Every note in a complex pattern has a reason. Play the pattern without the complexity and ask what\'s missing. Only add what\'s specifically missing.",
        },
        'meta': {'pairId': 'drum-simple-complex', 'pole': 'right', 'poleName': 'Complex', 'group': 'Complexity'},
    },
]

DRUMS_PROBLEMS = [
    {
        'id': 'kick-bass-fight',
        'type': 'problem',
        'title': 'Kick and Bass are Fighting',
        'oneLiner': 'The low end sounds muddy — kick and bass occupy the same space.',
        'filters': ['mixing'],
        'sections': {
            'cause': 'Cause: The kick sub (40–80Hz) and the bass fundamental (60–120Hz) are both occupying the same frequency band. When they hit simultaneously, they compete — neither sounds clear. The result is a muddy, undefined low end where nothing punches.',
            'fixSteps': [
                'Tune the kick to the root note of the song, or the fifth. An out-of-tune kick creates harmonic beating with the bass.',
                'High-pass the bass at 40Hz minimum — remove the infrasonic content that contributes nothing but headroom consumption.',
                'High-pass the kick character layer (not the sub layer) at 60–80Hz so the kick body doesn\'t double the bass fundamental.',
                'Apply frequency-specific sidechain: use Waves C6 or F6 in dynamic mode on the bass, triggered by the kick. Set a dynamic cut at 60–100Hz. Only that band ducks when the kick hits — the rest of the bass is unaffected.',
                'Check in mono. Phase cancellation between kick and bass is worse in mono. If the low end collapses when you sum to mono, the issue is phase, not just frequency.',
            ],
        },
        'meta': {'tag': 'Low End'},
    },
    {
        'id': 'thin-snare',
        'type': 'problem',
        'title': 'Snare Sounds Thin and Weak',
        'oneLiner': 'The snare has no body — it clicks without weight.',
        'filters': ['mixing'],
        'sections': {
            'cause': 'Cause: The snare sample is missing low-mid energy (200–400Hz body), or has been over-EQ\'d in the high end relative to its body. Or: the snare is sitting in a frequency range that\'s being masked by guitars, synths, or pads occupying the same space.',
            'fixSteps': [
                'Add a body layer: a snare sample with more 200–400Hz energy layered beneath the existing snare, at −6 to −12dB.',
                'Boost 200–300Hz gently (+2dB) on the snare channel for body and warmth.',
                'Add a noise layer: a 50ms white noise burst blended at −15dB adds the papery, organic quality that synthetic snares lack.',
                'Apply parallel compression: send the snare to a parallel return with heavy 1176-style compression. Blend 20–30% of the parallel signal back in for density.',
                'Check what else is in the 200–400Hz range. If a pad or guitar is occupying that space, carve 2–3dB from them at that frequency to make room for the snare body.',
            ],
        },
        'meta': {'tag': 'Snare'},
    },
    {
        'id': 'mechanical-hats',
        'type': 'problem',
        'title': 'Hi-Hats Sound Robotic',
        'oneLiner': 'The hats are metronomic and mechanical — they don\'t have groove.',
        'filters': ['midi', 'groove'],
        'sections': {
            'cause': 'Cause: All hi-hat notes are at the same velocity and land exactly on the grid. Real hi-hat playing has constant velocity variation (accent beats, ghost off-beats) and micro-timing variation. Without these, the hats sound like a metronome.',
            'fixSteps': [
                'Manually program velocity variation. Accent every on-beat hat (velocity 85–95). Ghost the off-beat hats (velocity 40–60). Mark phrase-ending hats with a slightly louder accent (velocity 100–110).',
                'Apply MPC swing to the hat pattern — 52–56% pushes alternate 16th notes slightly late, creating lope.',
                'Use open hi-hat notes on specific beats (the "and" of beat 2 or 4) for lift and variation — they should be at higher velocity than the closed hats around them.',
                'Trim the hat sample\'s sustain with Waves Transient Master (Sustain −2) if the hats are ringing too long — this separates the hits perceptually and creates better groove.',
                'Check hi-hat choke settings: the open hat should be choked by the closed hat note. If they\'re layering, the hat ringing becomes blurred and ungroovy.',
            ],
        },
        'meta': {'tag': 'Hi-Hats'},
    },
    {
        'id': 'no-groove',
        'type': 'problem',
        'title': 'Drums Have No Groove — Too Stiff',
        'oneLiner': 'The pattern is technically correct but doesn\'t make you move.',
        'filters': ['midi', 'groove'],
        'sections': {
            'cause': 'Cause: 100% quantization, uniform velocity, no timing variation. The pattern is rhythmically correct but has no human feel. Every element lands exactly where expected, which paradoxically makes the pattern feel less stable, not more — human listeners expect slight imperfection as a cue for "something is alive here."',
            'fixSteps': [
                'Apply groove quantization via Ableton Groove Pool: try MPC 16 Swing 54 at 60% Amount first. A/B against the quantized version. Your body will tell you which version wants to move.',
                'Add ghost notes to the snare: velocity 20–35 between the main hits. The ghost notes create the low-level conversation that makes patterns feel occupied.',
                'Offset the whole drum pattern 10–15ms late relative to the grid. This is the "behind the beat" feel. Counterintuitive but immediately audible.',
                'Manually vary kick velocity: main kick on beat 1 at 100, kick variation on beat 3 at 90, any additional kicks at 75–80.',
                'Listen to a reference track with a groove you like. Loop a 2-bar section and listen for where the snare lands relative to the grid. It\'s probably not on the grid.',
            ],
        },
        'meta': {'tag': 'Groove'},
    },
    {
        'id': 'drums-disappear',
        'type': 'problem',
        'title': 'Drums Disappear in the Mix',
        'oneLiner': 'Drums sound great in isolation but get buried when the arrangement comes in.',
        'filters': ['mixing'],
        'sections': {
            'cause': 'Cause: The drums lack elements that cut through dense arrangements. Missing high-frequency content (kick click, snare crack) that separates drums from guitars and synths. Or: the drums are being compressed too heavily on the bus, losing transients. Or: other elements are occupying the frequency space that drums need.',
            'fixSteps': [
                'Add or enhance the kick click layer: a sample or synthesized transient at 2–5kHz, blended beneath the main kick. This is what makes kicks audible on small speakers and in dense mixes.',
                'Boost 3–5kHz on the snare channel for crack that cuts through. This is the frequency that makes a snare audible in a full arrangement.',
                'Check the drum bus compressor: if the attack is very fast (under 10ms), it\'s catching and squashing the transients. Slow the attack to 30–60ms to let the kicks and snares punch through before compression engages.',
                'Apply parallel compression to the drum bus: blend 20% of a heavily compressed parallel signal into the main bus for density without losing transient impact.',
                'EQ carve: find where guitars, synths, or pads are masking the drum crack (often 2–5kHz). Cut 2–3dB from those elements at the frequency where the drums need to live.',
            ],
        },
        'meta': {'tag': 'Mixing'},
    },
    {
        'id': 'dated-mix',
        'type': 'problem',
        'title': 'Drum Mix Sounds Dated or Generic',
        'oneLiner': 'The drums give away the era of the sample pack — they don\'t sound current.',
        'filters': ['sound-design', 'mixing'],
        'sections': {
            'cause': 'Cause: Using drum samples with an obvious era signature without processing them into a current context. Or: using the default reverb settings of whatever DAW plugin was opened first. Or: no layering — relying on a single sample for each drum element, which lacks depth and dimension.',
            'fixSteps': [
                'Layer, don\'t replace. Even a single updated sample layered beneath the existing drum sound can modernize it. A current kick sub layer under an old kick body will update the low end immediately.',
                'Apply saturation to the drum bus (Waves J37 at low drive) — this adds harmonic character that moves the sound out of the default digital realm.',
                'Check the snare reverb: if it sounds like a specific era (the gated reverb of the 80s, the cathedral reverb of the 90s), the snare will immediately date the production. Remove or replace it.',
                'Compare against a current reference track at matched loudness. Identify what frequency range the reference has more or less of compared to your drums. Make one EQ adjustment at a time.',
                'Transient shaping: modern drum sounds are often sharper and more controlled than vintage sounds. Waves Transient Master, enhance attack by 1–2 points and reduce sustain by 1–2 points.',
            ],
        },
        'meta': {'tag': 'Production'},
    },
]
