export const state = {
  items: [],
  todaySuggestionIds: [],
  completedTodayCount: 0,
  lastCompletedDate: null,
  lastCategory: 'life',
  drillDownCategory: null,
  selectedIds: new Set(),
  searchQuery: '',
  undoItem: null,
  undoTimeout: null,
  editingId: null,
  pairId: null,
  addedBy: null,
  deviceSyncId: null,
  talkAboutItems: [],
  talkAboutUnsubscribe: null,
  prefsUnsubscribe: null,
  customLabels: {},
  columnColors: {},
  columnOrder: null,
  categoryPreset: 'generic',
  buttonColor: null,
  textColor: null,
  displayName: '',
  emailTriageItems: [],
  lastAgentRun: null,
  emailTriageUnsubscribe: null,
  savePrefsTimeout: null,
  processingIds: new Set(),
  expandingMetaCardId: null,
  addFromTalkItem: null,
  tallyResetHour: 3,
  piles: [],
  viewMode: 'columns',
  showSuggestNext: true,
  suggestNextStripTimeout: null,
  columnNotes: {},
  openColumnNoteId: null,
  columnNoteSaveTimeouts: {},
  lastSeed: null,
  seedRenderTaskCache: [],
  seedRenderState: null,
  seedReflections: [],
  habits: [],
  habitCompletions: [],
  journalDaily: {},
  journalActiveTab: 'daily',
  journalFocusMode: false,
  journalDailySaveTimeout: null,
  people: [],
  /** @type {{ id: string, label: string }[] | null} */
  peopleGroups: null,
  relationshipsDetailPersonId: null,
  /** Shown in Settings; set from `product.json` (no private URLs). */
  buildRef: '',
  /** Optional white-label copy from `product.json`. */
  productConfig: null
};
